In [ ]:
import torch
torch.__version__

'2.1.0+cu118'

In [ ]:
s = torch.tensor(7)
s

tensor(7)

In [ ]:
s.ndim

0

In [ ]:
s.item() #only for 1 elem tensor

7

In [ ]:
vec = torch.tensor([7,7])
vec

tensor([7, 7])

In [ ]:
vec.ndim

1

In [ ]:
vec.shape

torch.Size([2])

In [ ]:
mat = torch.tensor([[7,8],[9,10]])
mat

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
mat.ndim


2

In [ ]:
mat.shape

torch.Size([2, 2])

In [ ]:
tensor = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])

In [ ]:
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
rand = torch.rand(size = (3,4))

In [ ]:
rand

tensor([[0.8979, 0.1175, 0.1379, 0.0788],
        [0.3982, 0.1377, 0.5025, 0.8944],
        [0.7904, 0.7891, 0.0306, 0.2308]])

In [ ]:
rand.ndim

2

In [ ]:
rand_img = torch.rand(size = (224,224,3))
rand_img.shape, rand_img.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
zeros = torch.zeros(size = (3,4))
ones = torch.ones(size = (3,4))
zeros, ones

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [ ]:
zero_to_ten = torch.arange(start = 0, end = 10, step = 1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ten_z = torch.zeros_like(input = zero_to_ten)
ten_o = torch.ones_like(input= zero_to_ten)
ten_z, ten_o

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [ ]:
#torch.cuda means GPU (from Nvidia CUDA toolkit)
#some data types: torch.float32 or torch.float, torch.float16 or torch.half,
#torch.float64 or torch.double

#more bits means more precise, leads to more accurate model but slower to compute

In [ ]:
float32_tensor = torch.tensor([3.0,6.0,9.0],
                              dtype = None,
                              device = None,
                              requires_grad = False) #if true, operations on tensor are recorded

float32_tensor.shape, float32_tensor.dtype, float32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
float16_tensor = torch.tensor([3.0,6.0,9.0],
                              dtype = torch.float16)

float16_tensor.dtype

torch.float16

In [ ]:
rand_ten = torch.rand(3,4)

print(rand_ten)
print(f"Shape of tensor: {rand_ten.shape}")
print(f"datatype of tensor: {rand_ten.dtype}")
print(f"device of tensor: {rand_ten.device}")


tensor([[0.5469, 0.7640, 0.0860, 0.6784],
        [0.1085, 0.1113, 0.3375, 0.7376],
        [0.8818, 0.7003, 0.0259, 0.7313]])
Shape of tensor: torch.Size([3, 4])
datatype of tensor: torch.float32
device of tensor: cpu


In [ ]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor *10

tensor([10, 20, 30])

In [ ]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
tensor * tensor #elem wise mult

tensor([1, 4, 9])

In [ ]:
#use @ for mat mult. Mst have same inner dimensions, resulting mat has outer dimensions as shape

In [ ]:
tensor.shape

torch.Size([3])

In [ ]:
#elem wise
tensor *tensor

tensor([1, 4, 9])

In [ ]:
#mat mult
torch.matmul(tensor, tensor)
#or
tensor @tensor

tensor(14)

In [ ]:
#transpose
"""torch.transpose(input, dim0, dim1) - where input is the desired tensor to transpose and
  dim0 and dim1 are the dimensions to be swapped.
tensor.T - where tensor is the desired tensor to transpose."""

'torch.transpose(input, dim0, dim1) - where input is the desired tensor to transpose and \n  dim0 and dim1 are the dimensions to be swapped.\ntensor.T - where tensor is the desired tensor to transpose.'

In [ ]:
A = torch.tensor([[1,2],[3,4],[5,6]],
                 dtype = torch.float32)
B = torch.tensor([[7,10],[8,11],[9,12]],
                 dtype = torch.float32)

In [ ]:
print(A)
print(B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [ ]:
print(A)
print(B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
print(f"original shapes: A = {A.shape}, B = {B.shape}\n")
print(f"new shapes: A = {A.shape}, B = {B.T.shape}\n")
print(f"mutliplying: {A.shape}*{B.T.shape} so inner dim match\n")
print("Output:\n")
output = torch.matmul(A, B.T)
print(output)
print(f"Output shape = {output.shape}")

original shapes: A = torch.Size([3, 2]), B = torch.Size([3, 2])

new shapes: A = torch.Size([3, 2]), B = torch.Size([2, 3])

mutliplying: torch.Size([3, 2])*torch.Size([2, 3]) so inner dim match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])
Output shape = torch.Size([3, 3])


In [ ]:
#torch.mm() same as torch.matmul()
torch.mm(A, B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [ ]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print(f"min: {x.min()}")
print(f"max: {x.max()}")
print(f"mean: {x.type(torch.float32).mean()}") #need type for mean
print(f"sum: {x.sum()}")

min: 0
max: 90
mean: 45.0
sum: 450


In [ ]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [ ]:
print(f"index of max: {x.argmax()}")
print(f"index of min: {x.argmin()}")

index of max: 9
index of min: 0


In [ ]:
#change type
tens = torch.arange(10.,100.,10.)
tens.dtype

torch.float32

In [ ]:
tens16 = tens.type(torch.float16)
tens16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [ ]:
tensInt8 = tens.type(torch.int8)
tensInt8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [ ]:
#reshaping methods
"""
torch.reshape(input, shape)
Tensor.view(shape) #preview of new shape
torch.stack(tensors, dim = 0)         #concat tensors on specified dim
torch.squeeze(input)      #remove all dim with val 1
torch.unsqueeze(input, dim)           #returns input w/ dimension of val 1 added at dim
torch.permute(input, dims)            #returns view of original input with dimensions rearranged to dims
"""

'\ntorch.reshape(input, shape)\nTensor.view(shape) #preview of new shape\ntorch.stack(tensors, dim = 0)         #concat tensors on specified dim\ntorch.squeeze(input)      #remove all dim with val 1\ntorch.unsqueeze(input, dim)           #returns input w/ dimension of val 1 added at dim\ntorch.permute(input, dims)            #returns view of original input with dimensions rearranged to dims\n'

In [ ]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
z = x.view(1,7)   #points to the same data (changing z will change x)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [ ]:
x_stacked =torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [ ]:
print(f"prev tensor: {x_reshaped}")
print(f"prev shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"new tensor: {x_squeezed}")
print(f"new shape: {x_squeezed.shape}")

prev tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
prev shape: torch.Size([1, 7])
new tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
new shape: torch.Size([7])


In [ ]:
print(f"prev tensor: {x_squeezed}")
print(f"prev shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f"new tensor: {x_unsqueezed}")
print(f"new shape: {x_unsqueezed.shape}")

prev tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
prev shape: torch.Size([7])
new tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
new shape: torch.Size([1, 7])


In [ ]:
x_original = torch.rand(size = (224, 224, 3))

x_permuted = x_original.permute(2,0,1) #points to the original, just changed view

print(f"prev shape: {x_original.shape}")
print(f"new shape: {x_permuted.shape}")

prev shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
print(f"first sq brack:\n{x[0]}")
print(f"second sq brack:\n{x[0][0]}")
print(f"third sq brack:\n{x[0][0][0]}")

first sq brack:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
second sq brack:
tensor([1, 2, 3])
third sq brack:
1


In [ ]:
x[:,0], x[:,:,1]

(tensor([[1, 2, 3]]), tensor([[2, 5, 8]]))

In [ ]:
#np array to tensor
"torch.from_numpy(ndarray)"
#tensor to np array
"torch.Tensor.numpy()"

'torch.Tensor.numpy()'

In [ ]:
import numpy as np
arr = np.arange(1.0, 8.0)
tens = torch.from_numpy(arr)
arr, tens       #changing one won't change the other

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#np float arr default to 64, but pytorch default to 32, so will have to manually change
tens = torch.from_numpy(arr).type(torch.float32)

In [ ]:
tens2 = torch.ones(7)
numpy_tens = tens2.numpy()
tens2, numpy_tens     #changing one won't change the other

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#setting seed
torch.manual_seed(seed = 42)

In [ ]:
!nvidia-smi


Thu Dec  7 19:11:04 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   60C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
torch.cuda.device_count()

1

In [ ]:
"""Note: Putting a tensor on GPU using to(device) (e.g. some_tensor.to(device))
returns a copy of that tensor, e.g. the same tensor will be on CPU and GPU.
To overwrite tensors, reassign them:

some_tensor = some_tensor.to(device)"""

'Note: Putting a tensor on GPU using to(device) (e.g. some_tensor.to(device)) \nreturns a copy of that tensor, e.g. the same tensor will be on CPU and GPU. \nTo overwrite tensors, reassign them:\n\nsome_tensor = some_tensor.to(device)'

In [ ]:
tens = torch.tensor([1,2,3])
print(tensor, tensor.device)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu       #gpu are indexed from 0

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [ ]:
#can't use numpy in gpu device
tens_back_cpu = tensor_on_gpu.cpu().numpy()
tens_back_cpu

array([1, 2, 3])

In [ ]:
tens_back_cpu = tens_back_cpu + 1

In [ ]:
tensor_on_gpu, tens_back_cpu

(tensor([1, 2, 3], device='cuda:0'), array([2, 3, 4]))